apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: otel-demo
spec:
  benchmark: otel-demo
  load:
    loadType: "Users"
    loadValues: [5, 15, 25]
  resources:
    resourceType: "Instances"
    resourceValues: [1, 2, 3]
  slos:
    - name: dummy
      properties: {}
  execution:
    metric: capacity
    strategy:
      name: "FullSearch"
    duration: 900 # in seconds
    loadGenerationDelay: 30 # in seconds
    repetitions: 1
