apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: otel-demo
spec:
  sut:
    resources:
      - configMap:
         name: "otel-demo-configmap"
         files:
           - "frontend-deployment.yaml"
  loadGenerator:
    resources:
      - configMap:
         name: "otel-demo-configmap"
         files:
            - load-generator-deployment.yaml
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "frontend-deployment.yaml"
  loadTypes:
    - typeName: "Users"
      patchers:
        - type: "EnvVarPatcher"
          resource: "load-generator-deployment.yaml"
          properties:
            container: "load-generator"
            variableName: "LOCUST_USERS"
  slos:
    - name: "dummy"
      sloType: "generic"
      properties:
        externalSloUrl: "http://localhost:80"
        query: "fetch spans, samplingRatio: 10, scanLimitGBytes: 50
| filter request.is_root_span == true AND isNotNull(endpoint.name)
| makeTimeseries {p90 = percentile(duration, 90)}, bins: 120, by: { dt.system.sampling_ratio }"
        provider: "dynatrace"
        warmup: 60 # in seconds
        queryAggregation: "mean"
        repetitionAggregation: "median"
        operator: "lte"
        threshold: 500000000
