apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: uc4-flink
  labels:
    suite: theodolite-stream-processing
    benchmark: uc4
    sut: flink
spec:
  sut:
    resources:
      - configMap:
          name: "benchmark-resources-uc4-flink"
          files:
            - "input-topic.yaml"
            - "output-topic.yaml"
            - "aggregation-feedback-topic.yaml"
            - "configuration-topic.yaml"
            - "flink-configuration-configmap.yaml"
            - "taskmanager-deployment.yaml"
            - "taskmanager-service.yaml"
            - "service-monitor.yaml"
            - "jobmanager-service.yaml"
            - "jobmanager-deployment.yaml"
            #- "jobmanager-rest-service.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc4-load-generator"
          files:
            - "uc4-load-generator-deployment.yaml"
            - "uc4-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "taskmanager-deployment.yaml"
        - type: "EnvVarPatcher"
          resource: "jobmanager-deployment.yaml"
          properties:
            container: "jobmanager"
            variableName: "PARALLELISM"
    - typeName: TaskSlotsAndPodResources
      patchers:
        - type: ConfigMapYamlPatcher
          resource: flink-configuration-configmap.yaml
          properties:
            fileName: flink-conf.yaml
            variableName: taskmanager.numberOfTaskSlots
        - type: ResourceLimitPatcher
          resource: taskmanager-deployment.yaml
          properties:
            container: taskmanager
            limitedResource: cpu
            factor: 1000
            format: m
        - type: ResourceLimitPatcher
          resource: taskmanager-deployment.yaml
          properties:
            container: taskmanager
            limitedResource: memory
            factor: 4
            format: Gi
        - type: ConfigMapYamlPatcher
          resource: flink-configuration-configmap.yaml
          properties:
            fileName: flink-conf.yaml
            variableName: taskmanager.memory.process.size
            factor: 4
            suffix: Gb
        - type: "EnvVarPatcher"
          resource: "jobmanager-deployment.yaml"
          properties:
            container: "jobmanager"
            variableName: "PARALLELISM"
  loadTypes:
    - typeName: "NumNestedGroups"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc4-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_NESTED_GROUPS"
        - type: NumNestedGroupsLoadGeneratorReplicaPatcher
          resource: "uc4-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
            numSensors: "4"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        consumerGroup: theodolite-uc4-application-0.0.1
        threshold: 2000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
    - name: droppedRecords
      sloType: generic
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        externalSloUrl: "http://localhost:8082"
        promQLQuery: "sum(rate(flink_taskmanager_job_task_operator_numLateRecordsDropped[30s])) by(job)"
        warmup: 60 # in seconds
        queryAggregation: max
        repetitionAggregation: median
        operator: lte
        threshold: 100
