apiVersion: v1
kind: Service
metadata:
  name: titan-ccp-load-generator
  labels:
    app: titan-ccp-load-generator
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: titan-ccp-load-generator
  ports:
    - name: coordination
      port: 5701
      targetPort: 5701
      protocol: TCP
