apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: jobmanager
          image: ghcr.io/cau-se/theodolite-uc3-beam-flink:latest
          args: ["standalone-job", "--job-classname", "rocks.theodolite.benchmarks.uc3.beam.flink.Uc3BeamFlink",
                  "--parallelism=$(PARALLELISM)",
                  "--disableMetrics=$(DISABLE_METRICS)",
                  "--fasterCopy=$(FASTER_COPY)"]
          # optional arguments: ["--job-id", "<job id>", "--fromSavepoint", "/path/to/savepoint", "--allowNonRestoredState"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://theodolite-kafka-schema-registry:8081"
            - name: CHECKPOINTING
              value: "false"
            - name: PARALLELISM
              value: "1"
            - name: DISABLE_METRICS
              value: "false"
            - name: FASTER_COPY
              value: "true"
            - name: "FLINK_STATE_BACKEND"
              value: "rocksdb"
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager"
            - name: FLINK_PROPERTIES
              value: |+
                blob.server.port: 6124
                jobmanager.rpc.port: 6123
                taskmanager.rpc.port: 6122
                queryable-state.proxy.ports: 6125
                jobmanager.memory.process.size: 4Gb
                taskmanager.memory.process.size: 4Gb
                parallelism.default: 1 #TODO
          resources:
            limits:
              memory: 4Gi
              cpu: 1000m
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob-server
            - containerPort: 8081
              name: webui
            - containerPort: 9249
              name: metrics
          livenessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 30
            periodSeconds: 60
          securityContext:
            runAsUser: 9999
