apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: taskmanager
          image: ghcr.io/cau-se/theodolite-uc3-beam-flink:latest
          args: ["taskmanager"]
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager"
          resources:
            limits:
              memory: 4Gi
              cpu: 1000m
          ports:
            - containerPort: 6122
              name: rpc
            - containerPort: 6125
              name: query-state
            - containerPort: 9249
              name: metrics
          securityContext:
            runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
