apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: uc3-hazelcastjet
spec:
  appResource:
    - "uc3-hazelcastjet/uc3-hazelcastjet-deployment.yaml"
    - "uc3-hazelcastjet/uc3-hazelcastjet-service.yaml"
    #- "uc3-hazelcastjet/uc3-jmx-configmap.yaml"
    #- "uc3-hazelcastjet/uc3-service-monitor.yaml"
  loadGenResource:
    - "uc3-kstreams/uc3-load-generator-deployment.yaml"
    - "uc3-kstreams/uc3-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc3-hazelcastjet/uc3-hazelcastjet-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc3-kstreams/uc3-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: NumSensorsLoadGeneratorReplicaPatcher
          resource: "uc3-kstreams/uc3-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  kafkaConfig:
    bootstrapServer: "theodolite-cp-kafka:9092"
    topics:
      - name: "input"
        numPartitions: 40
        replicationFactor: 1
      - name: "output"
        numPartitions: 40
        replicationFactor: 1
