apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: uc3-hazelcastjet
  labels:
    suite: theodolite-stream-processing
    benchmark: uc3
    sut: hazelcastjet
spec:
  sut:
    resources:
      - configMap:
          name: "benchmark-resources-uc3-hazelcastjet"
          files:
            - "uc3-hazelcastjet-deployment.yaml"
            - "uc3-hazelcastjet-service.yaml"
            - "uc3-jmx-configmap.yaml"
            - "uc3-service-monitor.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc3-load-generator"
          files:
            - "uc3-load-generator-deployment.yaml"
            - "uc3-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc3-hazelcastjet-deployment.yaml"
    - typeName: PodResources
      patchers:
        - type: ResourceLimitPatcher
          resource: uc3-hazelcastjet-deployment.yaml
          properties:
            container: uc-application
            limitedResource: cpu
            factor: 1000
            format: m
        - type: ResourceLimitPatcher
          resource: uc3-hazelcastjet-deployment.yaml
          properties:
            container: uc-application
            limitedResource: memory
            factor: 4
            format: Gi
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc3-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: NumSensorsLoadGeneratorReplicaPatcher
          resource: "uc3-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        consumerGroup: theodolite-uc3-application
        threshold: 2000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  kafkaConfig:
    bootstrapServer: "theodolite-kafka-kafka-bootstrap:9092"
    topics:
      - name: "input"
        numPartitions: 100
        replicationFactor: 1
      - name: "output"
        numPartitions: 100
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
