{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "theodolite.fullname" . }}
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    - statefulsets
    verbs:
    - delete
    - deletecollection
    - list
    - get
    - create
    - update
  - apiGroups:
    - ""
    resources:
    - services
    - pods
    - configmaps
    verbs:
    - update
    - delete
    - deletecollection
    - list
    - get
    - create
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
    - get
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    - podmonitors
    verbs:
    - update
    - delete
    - deletecollection
    - list
    - create
    - get
  - apiGroups:
    - kafka.strimzi.io
    resources:
    - kafkatopics
    verbs:
    - delete
    - deletecollection
    - list
    - get
    - create
    - update
  {{- with .Values.rbac.additionalRules }}
{{ toYaml . | indent 2 }}
  {{- end }}
  {{- if .Values.operator.enabled }}
  - apiGroups:
    - theodolite.rocks
    resources:
    - benchmarks
    - benchmarks/status
    - executions
    - executions/status
    verbs:
    - delete
    - list
    - get
    - create
    - watch
    - update
    - patch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - delete
    - get
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
  {{- end }}
{{- end }}