{{- if .Values.operator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theodolite.fullname" . }}-operator
spec:
  selector:
    matchLabels:
      app: {{ include "theodolite.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "theodolite.fullname" . }}
      {{- with .Values.operator.podAnnotations }}
      annotations:
      {{ toYaml . | indent 2 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName:  {{ include "theodolite.serviceAccountName" . }}
      securityContext:
        runAsUser: 0 # Set the permissions for write access to the volumes.
      containers:
        - name: theodolite
          image: "{{ .Values.operator.image }}:{{ .Values.operator.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.imagePullPolicy }}"
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: MODE
              value: operator
            - name: RESULTS_FOLDER
              value: "/deployments/results"
            - name: QUARKUS_LOG_LEVEL
              value: {{ .Values.operator.logLevel | quote }}
            {{- if .Values.operator.prometheusUrl }}
            - name: THEODOLITE_PROMETHEUS_URL
              value: {{ .Values.operator.prometheusUrl | quote }}
            {{- end }}
            - name: THEODOLITE_SLO_CHECKER_URL
              value: {{ .Values.operator.sloCheckerUrl | default "http://localhost:8082" | quote }}
            {{- if .Values.operator.dynatrace.url }}
            - name: THEODOLITE_DYNATRACE_URL
              value: {{ .Values.operator.dynatrace.url | quote }}
            {{- end }}
            {{- if .Values.operator.dynatrace.existingSecret }}
            - name: DQL_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.operator.dynatrace.existingSecret }}
                  key: clientId
            - name: DQL_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.operator.dynatrace.existingSecret }}
                  key: clientSecret
            - name: DQL_SCOPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.operator.dynatrace.existingSecret }}
                  key: scope
            - name: DQL_RESOURCE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.operator.dynatrace.existingSecret }}
                  key: resource
            - name: DQL_AUTHURL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.operator.dynatrace.existingSecret }}
                  key: authUrl
            {{- else }}
            {{- if .Values.operator.dynatrace.clientId }}
            - name: DQL_CLIENTID
              value: {{ .Values.operator.dynatrace.clientId | quote }}
            {{- end }}
            {{- if .Values.operator.dynatrace.clientSecret }}
            - name: DQL_CLIENTSECRET
              value: {{ .Values.operator.dynatrace.clientSecret | quote }}
            {{- end }}
            {{- if .Values.operator.dynatrace.scope }}
            - name: DQL_SCOPE
              value: {{ .Values.operator.dynatrace.scope | quote }}
            {{- end }}
            {{- if .Values.operator.dynatrace.resource }}
            - name: DQL_RESOURCE
              value: {{ .Values.operator.dynatrace.resource | quote }}
            {{- end }}
            {{- if .Values.operator.dynatrace.authUrl }}
            - name: DQL_AUTHURL
              value: {{ .Values.operator.dynatrace.authUrl | quote }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: theodolite-results-volume
              mountPath: "/deployments/results"
          {{- with .Values.operator.resources}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
        {{- if .Values.operator.sloChecker.generic.enabled }}
        - name: slo-checker-generic
          image: "{{ .Values.operator.sloChecker.generic.image }}:{{ .Values.operator.sloChecker.generic.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.sloChecker.generic.imagePullPolicy }}"
          ports:
          - containerPort: 8082
            name: slo-generic
          env:
          - name: PORT
            value: "8082"
          - name: LOG_LEVEL
            value: INFO
          {{- with .Values.operator.sloChecker.generic.resources}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
        {{- end }}
        {{- if .Values.operator.sloChecker.lagTrend.enabled }}
        - name: lag-trend-slo-checker
          image: "{{ .Values.operator.sloChecker.lagTrend.image }}:{{ .Values.operator.sloChecker.lagTrend.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.sloChecker.lagTrend.imagePullPolicy }}"
          ports:
          - containerPort: 80
            name: slo-lag-trend
          env:
          - name: LOG_LEVEL
            value: INFO
          {{- with .Values.operator.sloChecker.lagTrend.resources}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
        {{- end }}
        {{- if .Values.operator.resultsVolume.accessSidecar.enabled }}
        - name: results-access
          image: "{{ .Values.operator.resultsVolume.accessSidecar.image }}:{{ .Values.operator.resultsVolume.accessSidecar.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.resultsVolume.accessSidecar.imagePullPolicy }}"
          command:
          - sh
          - -c
          - exec tail -f /dev/null
          volumeMounts:
          - mountPath: /results
            name: theodolite-results-volume
          {{- with .Values.operator.resultsVolume.accessSidecar.resources}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
        {{- end }}
      volumes:
      - name: theodolite-results-volume
        {{- if .Values.operator.resultsVolume.persistent.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "theodolite.resultsClaimName" . | quote }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
{{- end }}
