{{- if .Values.operator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theodolite.fullname" . }}-operator
spec:
  selector:
    matchLabels:
      app: {{ include "theodolite.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "theodolite.fullname" . }}
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName:  {{ include "theodolite.serviceAccountName" . }}
      securityContext:
        runAsUser: 0 # Set the permissions for write access to the volumes.
      containers:
        - name: theodolite
          image: "{{ .Values.operator.image }}:{{ .Values.operator.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.imagePullPolicy }}"
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: MODE
              value: operator
            - name: RESULTS_FOLDER
              value: "/deployments/results"
          volumeMounts:
            - name: theodolite-results-volume
              mountPath: "/deployments/results"
        {{- if .Values.operator.sloChecker.droppedRecordsKStreams.enabled }}
        - name: slo-checker-generic
          image: "{{ .Values.operator.sloChecker.generic.image }}:{{ .Values.operator.sloChecker.generic.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.sloChecker.generic.imagePullPolicy }}"
          ports:
          - containerPort: 8082
            name: analysis
          env:
          - name: PORT
            value: "8082"
          - name: LOG_LEVEL
            value: INFO
        {{- end }}
        {{- if .Values.operator.sloChecker.lagTrend.enabled }}
        - name: lag-trend-slo-checker
          image: "{{ .Values.operator.sloChecker.lagTrend.image }}:{{ .Values.operator.sloChecker.lagTrend.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.sloChecker.lagTrend.imagePullPolicy }}"
          ports:
          - containerPort: 80
            name: analysis
          env:
          - name: LOG_LEVEL
            value: INFO
        {{- end }}
        {{- if .Values.operator.sloChecker.droppedRecordsKStreams.enabled }}
        - name: slo-checker-dropped-records-kstreams
          image: "{{ .Values.operator.sloChecker.droppedRecordsKStreams.image }}:{{ .Values.operator.sloChecker.droppedRecordsKStreams.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.sloChecker.droppedRecordsKStreams.imagePullPolicy }}"
          ports:
          - containerPort: 8081
            name: analysis
          env:
          - name: PORT
            value: "8081"
          - name: LOG_LEVEL
            value: INFO
        {{- end }}
        {{- if .Values.operator.resultsVolume.accessSidecar.enabled }}
        - name: results-access
          image: busybox:stable
          image: "{{ .Values.operator.resultsVolume.accessSidecar.image }}:{{ .Values.operator.resultsVolume.accessSidecar.imageTag }}"
          imagePullPolicy: "{{ .Values.operator.resultsVolume.accessSidecar.imagePullPolicy }}"
          command:
          - sh
          - -c
          - exec tail -f /dev/null
          volumeMounts:
          - mountPath: /results
            name: theodolite-results-volume
        {{- end }}
      volumes:
      - name: theodolite-results-volume
        {{- if .Values.operator.resultsVolume.persistent.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "theodolite.resultsClaimName" . | quote }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
{{- end }}
