apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: theodolite-strimzi
spec:
  kafka:
    jmxOptions: {}
    storage:
      type: ephemeral
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  
  kafkaExporter: {}

  zookeeper:
    storage:
      type: ephemeral
