apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-exporter-podmonitor
  labels:
    app: theodolite
spec:
  selector:
    selector:
    matchLabels:
      strimzi.io/name: theodolite-strimzi-kafka-exporter
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus