{{- if .Values.strimzi.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-resources-metrics
  labels:
    app: theodolite
spec:
  selector:
    selector:
    matchLabels:
      strimzi.io/name: {{ template "theodolite.fullname" . }}-strimzi-kafka
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus
{{- end }}