apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-resources-metrics
  labels:
    app: theodolite
spec:
  selector:
    selector:
    matchLabels:
      strimzi.io/name: theodolite-strimzi-kafka
  namespaceSelector:
    matchNames:
      - default
