{{- if .Values.kcat.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "theodolite.fullname" . }}-kcat
spec:
  containers:
  - name: kcat
    image: edenhill/kcat:1.7.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
    env:
      - name: BOOTSTRAP_SERVER
        value: {{ template "theodolite.fullname" . }}-kafka-kafka-bootstrap:9092
  {{- with .Values.kcat.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
