{{- if .Values.strimzi.zookeeper.zooEntrance.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: zoo-entrance
  name: {{ template "theodolite.fullname" . }}-kafka-zoo-entrance
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: zoo-entrance
    ports:
    - port: 2181
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: {{ template "theodolite.fullname" . }}-kafka-zookeeper
  policyTypes:
  - Ingress
{{- end }}
