{
 "title": "Scalability Benchmarking",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "label": "Job",
    "query": "label_values(kafka_consumer_consumer_fetch_manager_metrics_records_lag, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec_topic_input)",
     "legendFormat": "{{Messages In Per Second}}"
    }
   ]
  },
  {
   "title": "Messages Out Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec_topic_output)",
     "legendFormat": "{{Messages Out Per Second}}"
    }
   ]
  },
  {
   "title": "Record Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(group, topic) (kafka_consumergroup_group_lag > 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count (kafka_consumer_consumer_fetch_manager_metrics_records_lag) by(pod))",
     "legendFormat": "instances"
    }
   ]
  },
  {
   "title": "Records Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(group,topic) (kafka_consumergroup_group_offset > 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(group,topic) (kafka_consumergroup_group_offset > 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records Produced (Kafka Lag Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(group,topic) (kafka_partition_latest_offset)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Partitions (Kafka Streams Export)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(job, topic) (kafka_consumer_consumer_fetch_manager_metrics_records_lag)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Record Lag (Kafka Streams Export)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, topic) (kafka_consumer_consumer_fetch_manager_metrics_records_lag)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Record Lag (Kafka Lag Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(group) (kafka_consumergroup_group_lag > 0)",
     "legendFormat": "total lag"
    }
   ]
  }
 ]
}