apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: uc3-kstreams
spec:
  sut:
    resources:
      - configMap:
          name: "benchmark-resources-uc3-kstreams"
          files:
          - "uc3-kstreams-deployment.yaml"
          - "uc3-kstreams-service.yaml"
          - "uc3-jmx-configmap.yaml"
          - "uc3-service-monitor.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc3-loadgen"
          files:
            - "uc3-load-generator-deployment.yaml"
            - "uc3-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc3-kstreams/uc3-kstreams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc3-kstreams/uc3-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: NumSensorsLoadGeneratorReplicaPatcher
          resource: "uc3-kstreams/uc3-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  kafkaConfig:
    bootstrapServer: "theodolite-cp-kafka:9092"
    topics:
      - name: "input"
        numPartitions: 40
        replicationFactor: 1
      - name: "output"
        numPartitions: 40
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
