{{- if .Values.prometheus.clusterRoleBinding.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "theodolite.fullname" . }}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "theodolite.fullname" . }}-prometheus
subjects:
- kind: ServiceAccount
  name: {{ template "theodolite.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
{{- end}}