{{- if and .Values.prometheus.enabled .Values.prometheus.nodePort.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "theodolite.fullname" . }}-prometheus-nodeport
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: {{ .Values.prometheus.nodePort.nodePort }}
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
{{- end}}
