{{- if not (index .Values "kube-prometheus-stack" "global" "rbac" "create") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "theodolite.fullname" . }}-kube-prometheus-operator
  labels:
    app: {{ template "theodolite.fullname" . }}-kube-prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "theodolite.fullname" . }}-kube-prometheus-operator
subjects:
- kind: ServiceAccount
  name: {{ template "theodolite.fullname" . }}-kube-prometheus-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
