{{- if .Values.prometheus.role.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.prometheus.role.clusterRole }}ClusterRole{{ else }}Role{{ end }}
metadata:
  name: {{ template "theodolite.fullname" . }}-prometheus
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
{{- if .Values.prometheus.role.clusterRole }}
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- end }}
{{- end }}
