{{- if .Values.prometheus.roleBinding.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "theodolite.fullname" . }}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "theodolite.fullname" . }}-prometheus
subjects:
- kind: ServiceAccount
  name: {{ template "theodolite.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
{{- end}}
