apiVersion: theodolite.com/v1alpha1
kind: benchmark
metadata:
  name: uc3-flink
appResource:
  - "uc3-flink/flink-configuration-configmap.yaml"
  - "uc3-flink/taskmanager-deployment.yaml"
  - "uc3-flink/taskmanager-service.yaml"
  - "uc3-flink/service-monitor.yaml"
  - "uc3-flink/jobmanager-service.yaml"
  - "uc3-flink/jobmanager-deployment.yaml"
  #- "uc3-flink/jobmanager-rest-service.yaml"
loadGenResource:
  - "uc3-kstreams/uc3-load-generator-deployment.yaml"
  - "uc3-kstreams/uc3-load-generator-service.yaml"
resourceTypes:
  - typeName: "Instances"
    patchers:
      - type: "ReplicaPatcher"
        resource: "uc3-flink/taskmanager-deployment.yaml"
      - type: "EnvVarPatcher"
        resource: "uc3-flink/jobmanager-deployment.yaml"
        container: "jobmanager"
        variableName: "PARALLELISM"
      - type: "EnvVarPatcher" # required?
        resource: "uc3-flink/taskmanager-deployment.yaml"
        container: "taskmanager"
        variableName: "PARALLELISM"
loadTypes:
  - typeName: "NumSensors"
    patchers:
      - type: "EnvVarPatcher"
        resource: "uc3-kstreams/uc3-load-generator-deployment.yaml"
        container: "workload-generator"
        variableName: "NUM_SENSORS"
      - type: NumSensorsLoadGeneratorReplicaPatcher
        resource: "uc3-kstreams/uc3-load-generator-deployment.yaml"
kafkaConfig:
  bootstrapServer: "theodolite-cp-kafka:9092"
  topics:
    - name: "input"
      numPartitions: 40
      replicationFactor: 1
    - name: "output"
      numPartitions: 40
      replicationFactor: 1
    - name: "theodolite-.*"
      removeOnly: True
