apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: uc2-kstreams
spec:
  appResource:
    - "uc2-kstreams/uc2-kstreams-deployment.yaml"
    - "uc2-kstreams/uc2-kstreams-service.yaml"
    - "uc2-kstreams/uc2-jmx-configmap.yaml"
    - "uc2-kstreams/uc2-service-monitor.yaml"
  loadGenResource:
    - "uc2-kstreams/uc2-load-generator-deployment.yaml"
    - "uc2-kstreams/uc2-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc2-kstreams/uc2-kstreams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc2-kstreams/uc2-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: NumSensorsLoadGeneratorReplicaPatcher
          resource: "uc2-kstreams/uc2-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "15000"
  kafkaConfig:
    bootstrapServer: "theodolite-cp-kafka:9092"
    topics:
      - name: "input"
        numPartitions: 40
        replicationFactor: 1
      - name: "output"
        numPartitions: 40
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
