apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: nginx-benchmark
  namespace: default
spec:
  # The system under test that will be started by Theodolite.
  sut:
    resources:
      - configMap:
          name: benchmark-configmap.yaml
          files:
            - "nginx-conf.yaml"
            - "nginx-deployment.yaml"
            - "nginx-service-monitor.yaml"
            - "nginx-log-exporter-config.yaml"
  # The deployment that will generate load for the SUT.
  loadGenerator:
    resources:
      - configMap:
          name: benchmark-configmap.yaml
          files:
            - "load-genenerator-deployment.yaml"
            - "nginx-service.yaml"
  # Patcher that controls the load intensity (in this case: the timeout for the curl service).
  loadTypes:
    - typeName: "curlTimeout"
      patchers:
        - type: "EnvVarPatcher"
          resource: "load-genenerator-deployment.yaml"
          properties:
            variableName: "TICKRATE"
            container: curl
  # Patcher that controls the number of instances (of the webserver).
  resourceTypes:
    # To increase the resources, add more instances of the webserver.
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "nginx-deployment.yaml"
