# Theodolite Random Scheduler

.random-scheduler:
  before_script:
    - cd utils/random-scheduler
  variables:
    IMAGE_NAME: theodolite-random-scheduler

package-random-scheduler:
  stage: package
  extends:
    - .random-scheduler
    - .kaniko-push
  needs: []
  rules:
    - changes:
      - utils/random-scheduler/**/*
      if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT"
    - if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT"
      when: manual
      allow_failure: true

publish-random-scheduler:
  stage: publish
  extends:
    - .random-scheduler
    - .crane-copy
  needs:
    - package-random-scheduler
  rules:
    - if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT && $CR_PUBLIC_HOST && $CR_PUBLIC_ORG && $CR_PUBLIC_USER && $CR_PUBLIC_PW"


# Theodolite Build Images

.buildimage-docker-compose-jq:
  variables:
    DOCKER_VERSION: 20.10.12
    BUILD_ARG_DOCKER_VERSION: $DOCKER_VERSION
    IMAGE_NAME: theodolite-build-docker-compose-jq
    IMAGE_TAG: $DOCKER_VERSION
  before_script:
    - cd utils/buildimages/docker-compose-jq

package-buildimage-docker-compose-jq:
  stage: package
  extends:
    - .buildimage-docker-compose-jq
    - .kaniko-push
  needs: []
  rules:
    - changes:
      - utils/buildimages/docker-compose-jq/Dockerfile
      if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT"
    - if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT && $CI_PIPELINE_SOURCE == 'web'"
      when: manual
      allow_failure: true

publish-buildimage-docker-compose-jq:
  stage: publish
  extends:
    - .buildimage-docker-compose-jq
    - .crane-copy
  needs:
    - package-buildimage-docker-compose-jq
  rules:
    - if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT && $CR_PUBLIC_HOST && $CR_PUBLIC_ORG && $CR_PUBLIC_USER && $CR_PUBLIC_PW && $CI_PIPELINE_SOURCE == 'web'"


.buildimage-k3d-helm:
  variables:
    DOCKER_VERSION: 20.10.12
    BUILD_ARG_DOCKER_VERSION: $DOCKER_VERSION
    BUILD_ARG_KUBECTL: v1.21.3
    IMAGE_NAME: theodolite-build-k3d-helm
    IMAGE_TAG: $DOCKER_VERSION
  before_script:
    - cd utils/buildimages/k3d-helm

package-buildimage-k3d-helm:
  stage: package
  extends:
    - .buildimage-k3d-helm
    - .kaniko-push
  needs: []
  rules:
    - changes:
      - utils/buildimages/k3d-helm/Dockerfile
      if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT"
    - if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT && $CI_PIPELINE_SOURCE == 'web'"
      when: manual
      allow_failure: true

publish-buildimage-k3d-helm:
  stage: publish
  extends:
    - .buildimage-k3d-helm
    - .crane-copy
  needs:
    - package-buildimage-k3d-helm
  rules:
    - if: "$CR_STAGE_HOST && $CR_STAGE_PROJECT && $CR_STAGE_USER && $CR_STAGE_PW && $CR_STAGE_CERT && $CR_PUBLIC_HOST && $CR_PUBLIC_ORG && $CR_PUBLIC_USER && $CR_PUBLIC_PW && $CI_PIPELINE_SOURCE == 'web'"
