apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: uc1-kstreams
spec:
  sut:
    resources:
      - configMap:
          name: "benchmark-resources-uc1-kstreams"
          files:
          - "uc1-kstreams-deployment.yaml"
          - "uc1-kstreams-service.yaml"
          - "uc1-jmx-configmap.yaml"
          - "uc1-service-monitor.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc1-load-generator"
          files:
          - "uc1-load-generator-deployment.yaml"
          - "uc1-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc1-kstreams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: NumSensorsLoadGeneratorReplicaPatcher
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        threshold: 2000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  kafkaConfig:
    bootstrapServer: "theodolite-kafka-kafka-bootstrap:9092"
    topics:
      - name: "input"
        numPartitions: 40
        replicationFactor: 1
