apiVersion: v1
kind: Service
metadata:
  name: titan-ccp-aggregation
  labels:
    app: titan-ccp-aggregation
spec:
  selector:
    app: titan-ccp-aggregation
  ports:
  - name: metrics
    port: 5556
