apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: titan-ccp-aggregation
    appScope: titan-ccp
  name: titan-ccp-aggregation
spec:
  selector:
    matchLabels:
        app: titan-ccp-aggregation
  endpoints:
    - port: metrics
      interval: 10s
