{
 "title": "Scalability Benchmarking (Flink)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages In Per Sec (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job_name) (flink_taskmanager_job_task_numRecordsInPerSecond)"
    }
   ]
  },
  {
   "title": "Messages Out Per Sec (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job_name) (flink_taskmanager_job_task_numRecordsOutPerSecond)"
    }
   ]
  },
  {
   "title": "Record Lag (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max)"
    }
   ]
  },
  {
   "title": "Record Lag (Flink Offset Difference)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (flink_taskmanager_job_task_operator_KafkaConsumer_topic_partition_currentOffsets - flink_taskmanager_job_task_operator_KafkaConsumer_topic_partition_committedOffsets)"
    }
   ]
  },
  {
   "title": "Input Queue Length (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, subtask_index) (flink_taskmanager_job_task_buffers_inputQueueLength)"
    }
   ]
  },
  {
   "title": "Output Queue Length (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, subtask_index) (flink_taskmanager_job_task_buffers_outputQueueLength)"
    }
   ]
  },
  {
   "title": "Number Of Instances (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "Backpressure (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_isBackPressured"
    }
   ]
  }
 ]
}