apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: example-benchmark
spec:
  sut:
    resources:
      - configMap:
         name: "benchmark-resources-uc1-kstreams"
         files:
           - "input-topic.yaml"
           - "uc1-kstreams-deployment.yaml"
           - "uc1-kstreams-service.yaml"
           - "uc1-jmx-configmap.yaml"
           - "uc1-service-monitor.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc1-load-generator"
          files:
            - uc1-load-generator-service.yaml
            - uc1-load-generator-deployment.yaml
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc1-kstreams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            variableName: "NUM_SENSORS"
            container: "workload-generator"
        - type: "NumSensorsLoadGeneratorReplicaPatcher"
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      properties:
        query: "sum by(job) (kafka_streams_stream_task_metrics_dropped_records_total>=0)"
        provider: "prometheus"
#        query: "timeseries avg(dt.kubernetes.container.cpu_usage), by: {k8s.pod.name, k8s.container.name}"
#        queryAggregation: "max"
#        repetitionAggregation: "max"
#        operator: "lte"
        threshold: 3000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
