apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: uc1-kstreams
spec:
  appResourceSets:
    - configMap:
       name: "example-configmap"
       files:
         - "uc1-kstreams-deployment.yaml"
  loadGenResourceSets:
    - configMap:
       name: "example-configmap"
       files:
          - uc1-load-generator-service.yaml
          - uc1-load-generator-deployment.yaml
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "custom/uc1-kstreams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "custom/uc1-load-generator-deployment.yaml"
          properties:
            variableName: "NUM_SENSORS"
            container: "workload-generator"
        - type: "NumSensorsLoadGeneratorReplicaPatcher"
          resource: "custom/uc1-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  kafkaConfig:
    bootstrapServer: "theodolite-cp-kafka:9092"
    topics:
      - name: "input"
        numPartitions: 40
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
  appResourceSets:
    # - fileSystem:
    #      path: ./../../../../../../config
    #      files:
    #        - "uc1-kstreams-deployment.yaml"
    #        - "aggregation-service.yaml"
    #        - "jmx-configmap.yaml"
    #        - "uc1-service-monitor.yaml"
    - configMap:
       name: "example-configmap"
       files:
         - "uc1-kstreams-deployment.yaml"
  loadGenResourceSets:
    # - fileSystem:
    #     path: ./../../../../../../config
    #     files:
    #       - uc1-load-generator-service.yaml
    #       - uc1-load-generator-deployment.yaml
    - configMap:
       name: "example-configmap"
       files:
          - uc1-load-generator-service.yaml
          - uc1-load-generator-deployment.yaml
