apiVersion: theodolite.rocks/v1beta2
kind: benchmark
metadata:
  name: example-benchmark
spec:
  sut:
    resources:
      - configMap:
         name: "example-configmap"
         files:
           - "uc1-input-topic.yaml"
           - "uc1-kstreams-deployment.yaml"
  loadGenerator:
    resources:
      - configMap:
         name: "example-configmap"
         files:
            - uc1-load-generator-service.yaml
            - uc1-load-generator-deployment.yaml
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc1-kstreams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: "NumSensorsLoadGeneratorReplicaPatcher"
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  slis:
    - name: consumerLag
      provider: prometheus
      query: "sum by(consumergroup) (kafka_consumergroup_lag{consumergroup='theodolite-uc1-application-0.0.1'} >= 0)"
  slos:
    - name: "lag trend"
      sli: consumerLag
      warmupSeconds: 60
      externalSloChecker: "http://localhost:80/evaluate-slope"
      threshold: 3000
