apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: theodolite-example-execution
spec:
  benchmark: "example-benchmark"
  loads:
    loadType: "NumSensors"
    loadValues: [25000, 50000, 75000, 100000, 125000, 150000]
  resources:
    resourceType: "Instances"
    resourceValues: [1, 2, 3, 4, 5]
  slos:
    - name: "lag trend"
      properties:
        threshold: 2000
  execution:
    strategy:
      name: "RestrictionSearch"
      restrictions:
        - "LowerBound"
      searchStrategy: "LinearSearch"
    duration: 300 # in seconds
    repetitions: 1
    loadGenerationDelay: 30 # in seconds
  configOverrides: []
  # - patcher:
  #     type: "NodeSelectorPatcher"
  #     resource: "uc1-load-generator-deployment.yaml"
  #     properties:
  #       variableName: "env"
  #     value: "prod"
  # - patcher:
  #     type: "NodeSelectorPatcher"
  #     resource: "uc1-kstreams-deployment.yaml"
  #     properties:
  #       variableName: "env"
  #   value: "prod"
  # - patcher:
  #     type: "ResourceLimitPatcher"
  #     resource: "uc1-kstreams-deployment.yaml"
  #     properties:
  #       container: "uc-application"
  #       limitedResource: "cpu"
  #   value: "1000m"
  # - patcher:
  #     type: "ResourceLimitPatcher"
  #     resource: "uc1-kstreams-deployment.yaml"
  #     properties:
  #       container: "uc-application"
  #       limitedResource: "memory"
  #   value: "2Gi"
  #  - patcher:
  #      type: "SchedulerNamePatcher"
  #      resource: "uc1-kstreams-deployment.yaml"
  #    value: "random-scheduler"
