apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: uc1-kstreams
spec:
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc1-kstreams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            variableName: "NUM_SENSORS"
            container: "workload-generator"
        - type: "NumSensorsLoadGeneratorReplicaPatcher"
          resource: "uc1-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "15000"
  kafkaConfig:
    bootstrapServer: "theodolite-cp-kafka:9092"
    topics:
      - name: "input"
        numPartitions: 40
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
        numPartitions: 0
        replicationFactor: 0
  appResourceSets:
    - name: TestAppResources
      FileSystemResourceSet:
        path: ./config
        files:
          - "uc1-kstreams-deployment.yaml"
          - "aggregation-service.yaml"
          - "jmx-configmap.yaml"
          - "uc1-service-monitor.yaml"
  loadGenResourceSets:
    - name: RestGenResources
      ConfigMapResourceSet:
        configmap: "test-configmap"
        files:
          - uc1-load-generator-service.yaml
          - uc1-load-generator-deployment.yaml
    