apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: uc2-beam-samza
  labels:
    suite: theodolite-stream-processing
    benchmark: uc2
    sut: beam-samza
spec:
  sut:
    resources:
      - configMap:
          name: "benchmark-resources-uc2-beam-samza"
          files:
          - "input-topic.yaml"
          - "output-topic.yaml"
          - "uc2-beam-samza-deployment.yaml"
          - "beam-samza-service.yaml"
          - "service-monitor.yaml"
          - "uc2-jmx-configmap.yaml"
    afterActions:
      - exec:
          selector: # delete zookeeper nodes to reset zookeeper
            pod:
              matchLabels:
                app: "zookeeper-client"
            container: "zookeeper-client"
          command: ["bash", "-c", "bin/zkCli.sh -server $ZOOKEEPER_SERVER deleteall /app-theodolite-uc2-application-1"]
          timeoutSeconds: 60
      - delete:
          selector:
            apiVersion: kafka.strimzi.io/v1beta2
            kind: KafkaTopic
            nameRegex: ".*samza.*"
      - delete:
          selector:
            apiVersion: kafka.strimzi.io/v1beta2
            kind: KafkaTopic
            nameRegex: ".*uc2-application.*"
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc2-load-generator"
          files:
          - "uc2-load-generator-deployment.yaml"
          - "uc2-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc2-beam-samza-deployment.yaml"
    - typeName: ThreadsAndPodResources
      patchers:
        - type: EnvVarPatcher
          resource: uc2-beam-samza-deployment.yaml
          properties:
            container: uc2-beam-samza
            variableName: SAMZA_JOB_CONTAINER_THREADS_POOL_SIZE
        - type: ResourceLimitPatcher
          resource: uc2-beam-samza-deployment.yaml
          properties:
            container: uc2-beam-samza
            limitedResource: cpu
            factor: 1000
            format: m
        - type: ResourceLimitPatcher
          resource: uc2-beam-samza-deployment.yaml
          properties:
            container: uc2-beam-samza
            limitedResource: memory
            factor: 4
            format: Gi
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc2-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: NumSensorsLoadGeneratorReplicaPatcher
          resource: "uc2-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        consumerGroup: theodolite-uc2-application
        threshold: 2000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
