apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-service-monitor
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    # - port: nginx-status-exporter-port
    #   interval: 10s
    - port: nginx-log-exporter-port
      interval: 10s
