apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-log-exporter-config
data:
  config.hcl: |
    listen {
      port = 4040
    }

    namespace "nginx" {
      source = {
        # syslog {
        #   listen_address = "udp://127.0.0.1:5531"
        #   format = "rfc3164"
        # }
        files = ["/var/log/nginx/access.log"]
      }

      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" rt=$request_time uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\" urt=\"$upstream_response_time\""

      labels {
        app = "default"
      }
    }