apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: public
      port: 80
      targetPort: 4000
    # - name: nginx-status-exporter-port
    #   port: 9113
    #   targetPort: 9113
    - name: nginx-log-exporter-port
      port: 4040
      targetPort: 4040
