apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf # mount nginx-conf volumn to /etc/nginx
              subPath: nginx.conf
              readOnly: true
            - name: nginx-logs
              mountPath: /var/log/nginx/
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: httpbin
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
        # - name: nginx-status-exporter
        #   image: nginx/nginx-prometheus-exporter
        #   imagePullPolicy: IfNotPresent
        #   resources:
        #     limits:
        #       memory: "128Mi"
        #       cpu: "100m"
        #   ports:
        #     - containerPort: 9113
        #   args:
        #     - -nginx.scrape-uri=http://localhost:4000/stub_status
        - name: nginx-log-exporter
          image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1
          args: ["-config-file", "/etc/prometheus-nginxlog-exporter/config.hcl"]
          ports:
            - containerPort: 4040
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: nginx-log-exporter-config
              mountPath: /etc/prometheus-nginxlog-exporter
            - name: nginx-logs
              mountPath: /var/log/nginx/
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-log-exporter-config
          configMap:
            name: nginx-log-exporter-config
        - name: nginx-logs
          emptyDir: {}
