apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;

    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;

    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      
      log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                         '"$request" $status $body_bytes_sent '
                         '"$http_referer" "$http_user_agent" '
                         'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

      access_log  /var/log/nginx/access.log  upstream_time;
      #access_log syslog:server=127.0.0.0:5531 upstream_time;
      access_log /dev/stdout upstream_time;
      
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen       4000;

        server_name  localhost;

        location / {
          
          proxy_pass        http://localhost:80/delay/1;

          proxy_connect_timeout       10;
          proxy_send_timeout          10;
          proxy_read_timeout          10;

          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
        }

        location = /stub_status {
            stub_status on;
        }

      }
    }
