apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-aggregation
  labels:
    app: titan-ccp-aggregation
spec:
  type: ClusterIP
  clusterIP: None
  selector:    
    app: titan-ccp-aggregation
  ports:  
    - name: coordination
      port: 5701
      targetPort: 5701
      protocol: TCP
    - name: metrics
      port: 5556

