apiVersion: theodolite.com/v1
kind: execution
metadata:
  name: uc3-flink-template
spec:
  benchmark: "uc3-flink"
  load:
    loadType: "NumSensors"
    loadValues: [100]
  resources:
    resourceType: "Instances"
    resourceValues: [1]
  slos:
    - sloType: "lag trend percent"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        percent: 0.05
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  execution:
    strategy: "LinearSearch"
    duration: 300 # in seconds
    repetitions: 1
    loadGenerationDelay: 30 # in seconds
    restrictions:
      - "LowerBound"
  configOverrides:
    - patcher:
        type: "ResourceLimitPatcher"
        resource: "uc3-flink/jobmanager-deployment.yaml"
        properties:
          container: "jobmanager"
          limitedResource: "cpu"
      value: "200m"
    - patcher:
        type: "ResourceLimitPatcher"
        resource: "uc3-flink/jobmanager-deployment.yaml"
        properties:
          container: "jobmanager"
          limitedResource: "memory"
      value: "1Gi"
    - patcher:
        type: "ResourceLimitPatcher"
        resource: "uc3-flink/taskmanager-deployment.yaml"
        properties:
          container: "taskmanager"
          limitedResource: "cpu"
      value: "200m"
    - patcher:
        type: "ResourceLimitPatcher"
        resource: "uc3-flink/taskmanager-deployment.yaml"
        properties:
          container: "taskmanager"
          limitedResource: "memory"
      value: "1Gi"