apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: uc3-flink
  labels:
    suite: theodolite-stream-processing
    benchmark: uc3
    sut: flink
spec:
  sut:
    resources:
      - configMap:
          name: "benchmark-resources-uc3-flink"
          files:
            - "flink-configuration-configmap.yaml"
            - "taskmanager-deployment.yaml"
            - "taskmanager-service.yaml"
            - "service-monitor.yaml"
            - "jobmanager-service.yaml"
            - "jobmanager-deployment.yaml"
            # - "jobmanager-rest-service.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc3-load-generator"
          files:
            - "uc3-load-generator-deployment.yaml"
            - "uc3-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "taskmanager-deployment.yaml"
        - type: "EnvVarPatcher"
          resource: "jobmanager-deployment.yaml"
          properties:
            container: "jobmanager"
            variableName: "PARALLELISM"
    - typeName: TaskSlotsAndPodResources
      patchers:
        - type: ConfigMapYamlPatcher
          resource: flink-configuration-configmap.yaml
          properties:
            fileName: flink-conf.yaml
            variableName: taskmanager.numberOfTaskSlots
        - type: ResourceLimitPatcher
          resource: taskmanager-deployment.yaml
          properties:
            container: taskmanager
            limitedResource: cpu
            factor: 1000
            format: m
        - type: ResourceLimitPatcher
          resource: taskmanager-deployment.yaml
          properties:
            container: taskmanager
            limitedResource: memory
            factor: 4
            format: Gi
        - type: ConfigMapYamlPatcher
          resource: flink-configuration-configmap.yaml
          properties:
            fileName: flink-conf.yaml
            variableName: taskmanager.memory.process.size
            factor: 4
            suffix: Gb
        - type: "EnvVarPatcher"
          resource: "jobmanager-deployment.yaml"
          properties:
            container: "jobmanager"
            variableName: "PARALLELISM"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc3-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_SENSORS"
        - type: NumSensorsLoadGeneratorReplicaPatcher
          resource: "uc3-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
    - typeName: "AggregationDurationDays"
      patchers:
        - type: "EnvVarPatcher"
          resource: "jobmanager-deployment.yaml"
          properties:
            container: "jobmanager"
            variableName: "AGGREGATION_DURATION_DAYS"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        consumerGroup: theodolite-uc3-application-0.0.1
        threshold: 2000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  kafkaConfig:
    bootstrapServer: "theodolite-kafka-kafka-bootstrap:9092"
    topics:
      - name: "input"
        numPartitions: 100
        replicationFactor: 1
      - name: "output"
        numPartitions: 100
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
