apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: test
  ports:
    - name: coordination
      port: 5701
      targetPort: 5701
      protocol: TCP
