apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-aggregation
spec:
  selector:
    matchLabels:
      app: titan-ccp-aggregation
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-aggregation
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: uc-application
          image: ghcr.io/cau-se/theodolite-uc1-kstreams-app:latest
          ports:
            - containerPort: 5555
              name: jmx
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://theodolite-kafka-schema-registry:8081"
            - name: JAVA_OPTS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555"
            - name: COMMIT_INTERVAL_MS # Set as default for the applications
              value: "100"
          resources:
            limits:
              memory: 4Gi
              cpu: 1000m