# Theodolite Helm Chart

lint-helm:
  stage: check
  needs: []
  image:
    name: alpine/helm:3.5.2
    entrypoint: [""]
  script: helm lint helm/
  rules:
  - changes:
    - helm/**/*
  - when: manual
    allow_failure: true

test-helm:
  stage: smoketest
  extends: .dind
  needs:
    - lint-helm
    # - job: package-theodolite
    #   optional: true
  image: ghcr.io/cau-se/theodolite-build-k3d-helm:20.10.12
  variables:
    CLUSTERNAME: "$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  cache:
    paths:
      - helm/charts
  before_script:
    - k3d help
    - k3d version
    - k3d cluster create $CLUSTERNAME --agents 1 --wait -p "30000:30000@agent:0" # k3d 5.0
    # show cluster info
    - kubectl cluster-info
    - helm version
  script:
    - cd helm
    - helm dependencies update .
    - helm install theodolite . -f preconfigs/minimal.yaml --wait # ${PACKAGE_THEODOLITE:+-f operator.image=$STAGE_IMAGE -f operator.imageTag=ci-"$CI_PIPELINE_ID"}
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide
    - helm test theodolite
  after_script:
    - k3d cluster delete $CLUSTERNAME
