apiVersion: v1
data:
  jmx-kafka-prometheus.yml: |
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
kind: ConfigMap
metadata:
  name: theodolite-cp-kafka-jmx-configmap
  namespace: default
