# Theodolite Docs

.docs:
  image: alpine/bundle:3.0.3
  cache:
    paths:
      - docs/vendor
  before_script:
    - cd docs
    - bundle config set --local path 'vendor'
    - bundle install
  rules:
    - changes:
      - docs/**/*
    - when: manual
      allow_failure: true

build-docs:
  stage: build
  extends: .docs
  script: bundle exec jekyll build
  artifacts:
    paths:
      - docs/_site

test-docs-links:
  stage: test
  extends: .docs
  needs:
    - build-docs
  script: bundle exec htmlproofer --assume-extension --allow_hash_href --http-status-ignore 999 ./_site

build-docs-crds:
  stage: build
  image:
    name: ghcr.io/fybrik/crdoc:0.6.1
    entrypoint: [""]
  script: /crdoc --resources theodolite/crd/ --template docs/api-reference/crds.tmpl --output docs/api-reference/crds.ref.md
  artifacts:
    paths:
      - docs/api-reference/crds.ref.md
    expire_in: 1 week
  rules:
    - changes:
      - docs/api-reference/crds.tmpl
      - theodolite/crd/**/*
    - when: manual
      allow_failure: true

test-docs-crds-regression:
  stage: test
  needs:
    - build-docs-crds
  image: alpine:3.15
  before_script:
    - cd docs
  script:
    - cmp api-reference/crds.md api-reference/crds.ref.md
  artifacts:
    when: on_failure
    paths:
      - docs/api-reference/crds.ref.md
    expire_in: 1 week
