{{- if .Values.randomScheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theodolite.fullname" . }}-random-scheduler
  labels:
    app: {{ include "theodolite.fullname" . }}
    component: random-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "theodolite.fullname" . }}
      component: random-scheduler
  template:
    metadata:
      labels:
        app: {{ include "theodolite.fullname" . }}
        component: random-scheduler
    spec:
      serviceAccount: {{ include "theodolite.fullname" . }}-random-scheduler
      containers:
        - name: random-scheduler
          image: "{{ .Values.randomScheduler.image }}:{{ .Values.randomScheduler.imageTag }}"
          imagePullPolicy: "{{ .Values.randomScheduler.imagePullPolicy }}"
          env:
            - name: TARGET_NAMESPACE
              value: {{ .Release.Namespace }}
      {{- with .Values.randomScheduler.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
{{- end }}
