{{- if and .Values.randomScheduler.enabled .Values.randomScheduler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: {{ include "theodolite.fullname" . }}-random-scheduler 
  labels:
    app: {{ include "theodolite.fullname" . }}
    component: random-scheduler
{{- end }}
