apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: uc4-beam-samza
  labels:
    suite: theodolite-stream-processing
    benchmark: uc4
    sut: beam-samza
spec:
  sut:
    resources:
      - configMap:
          name: "benchmark-resources-uc4-beam-samza"
          files:
          - "uc4-beam-samza-deployment.yaml"
          - "beam-samza-service.yaml"
          - "service-monitor.yaml"
          - "uc4-jmx-configmap.yaml"
    afterActions:
      - exec:
          selector: # delete zookeeper nodes to reset zookeeper
            pod:
              matchLabels:
                app: "zookeeper-client"
            container: "zookeeper-client"
          command: ["bash", "-c", "bin/zkCli.sh -server $ZOOKEEPER_SERVER deleteall /app-theodolite-uc4-application-1"]
          timeoutSeconds: 60
  loadGenerator:
    resources:
      - configMap:
          name: "benchmark-resources-uc4-load-generator"
          files:
          - "uc4-load-generator-deployment.yaml"
          - "uc4-load-generator-service.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "uc4-beam-samza-deployment.yaml"
  loadTypes:
    - typeName: "NumNestedGroups"
      patchers:
        - type: "EnvVarPatcher"
          resource: "uc4-load-generator-deployment.yaml"
          properties:
            container: "workload-generator"
            variableName: "NUM_NESTED_GROUPS"
        - type: NumNestedGroupsLoadGeneratorReplicaPatcher
          resource: "uc4-load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
            numSensors: "4.0"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        consumerGroup: theodolite-uc4-application
        threshold: 2000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  kafkaConfig:
    bootstrapServer: "theodolite-kafka-kafka-bootstrap:9092"
    topics:
      - name: "input"
        numPartitions: 40
        replicationFactor: 1
      - name: "output"
        numPartitions: 40
        replicationFactor: 1
      - name: "configuration"
        numPartitions: 40
        replicationFactor: 1
      - name: "aggregation-feedback"
        numPartitions: 40
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
      - name: ".*samza.*"
        removeOnly: true
      - name: ".*uc4-application.*"
        removeOnly: true